<?php
/**
 * @file
 * dopcom.features.inc
 */

/**
 * Implements hook_views_api().
 */
function dopcom_views_api() {
  return array("version" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function dopcom_node_info() {
  $items = array(
    'article' => array(
      'name' => t('Article'),
      'base' => 'node_content',
      'description' => t('Utilisez les <em>articles</em> pour des contenus possédant une temporalité tels que des actualités, des communiqués de presse ou des billets de blog.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'evenement' => array(
      'name' => t('Evenement'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
